### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by Denominator13** [FelipeVieiraVendramini/AutoUpdater#3]
So I'm not sure what is actually happening but it seems the older version is trying to download the patch 1001.exe to C://Program Files(x86)/AnarchyConquer but as 1001,rar then telling me it's corrupted, also a Readme would be great :)

**Comment by Denominator13** [comment]
I have downloaded the newer version but I'm getting an System.IndexOutOfRangeException: Index was outside the bounds of the array. when I try to open Autoupdater.exe so I tested with debugging and it's thrown at line 882 in AutoUpdater FrmMain.cs, I'm guessing it's to do with not connecting to the server so then I am thinking perhaps a firewall issue?

So I've checked everything possible and the only thing that has actually changed is the OS, worked fine on Win 10 but Win 11 just gives my computer so many problems :/

**Comment by wmgm183** [comment]
> 所以我不确定到底发生了什么，但似乎旧版本正在尝试将补丁 1001.exe 下载到 C://Program Files(x86)/AnarchyConquer 但作为 1001,rar 然后告诉我它已损坏，也是自述文件会很棒:)

How to configure the update. Can you explain it in detail, please?
